### Create an exercise (Admin only)
POST {{url}}/exercise
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "name": "Bench Press",
  "description": "Chest exercise using barbell",
  "muscleGroup": "Chest",
  "equipment": "Barbell",
  "difficulty": "HARD"
}

### Get all exercises (User/Admin)
GET {{url}}/exercise
Authorization: Bearer {{jwt_token}}

### Get exercise by ID (User/Admin)
GET {{url}}/exercise/1
Authorization: Bearer {{jwt_token}}

### Update exercise (Admin only)
PUT {{url}}/exercise/2
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "name": "Incline Bench Press",
  "description": "Chest exercise on incline bench",
  "muscleGroup": "Chest",
  "equipment": "Barbell",
  "difficulty": "HARD"
}

### Delete exercise (Admin only)
DELETE {{url}}/exercise/2
Authorization: Bearer {{jwt_token}}
