### A simple get request to the test endpoint. No need for login
GET {{url}}/auth/test/

### Populate the database with some data
//GET {{url}}//populate/

### Create a new user - this one will only get a USER role by default
POST {{url}}/auth/register/

{
    "username": "Gruppe18",
    "password": "pass12345"
}

###
POST {{url}}/auth/login/

{
    "username": "Gruppe18",
    "password": "pass12345"
}

> {%
    client.global.set("jwt_token", response.body.token);
    console.log("JWT Token:", client.global.get("jwt_token"));
%}

###
GET {{url}}/protected/user_demo/
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJcInBoaWxpcDE5OTNcIiIsInN1YiI6IkdydXBwZTE4IiwiZXhwIjoxNzYxMTMxOTE3LCJyb2xlcyI6IlVzZXIiLCJ1c2VybmFtZSI6IkdydXBwZTE4In0.Z3u-L1nJOnIYfAgJn8ieM8_f8foLE_sH1eyLyh7O1ZY

###
GET {{url}}/protected/admin_demo/
Accept: application/json
Authorization: Bearer {{jwt_token}}

### Add admin role to user
POST {{url}}/auth/user/addrole/
Accept: application/json
Authorization: Bearer {{jwt_token}}

{
    "role": "admin"
}
Accept: application/json
Authorization: Bearer {{jwt_token}}
