### Create week (Admin only)
POST {{url}}/week
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "weekNumber": 9,
  "days": []
}

### Get all weeks (User/Admin)
GET {{url}}/week
Authorization: Bearer {{jwt_token}}

### Get week by id (User/Admin)
GET {{url}}/week/1
Authorization: Bearer {{jwt_token}}

### Update week (Admin only)
PUT {{url}}/week/9
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "weekNumber": 2,
  "days": []
}

### Delete week (Admin only)
DELETE {{url}}/week/1
Authorization: Bearer {{jwt_token}}
