### Create week
POST http://localhost:7076/api/v1/week
Content-Type: application/json

{
  "weekNumber": 3,
  "days": []
}

### Get all weeks
GET http://localhost:7076/api/v1/week
Content-Type: application/json
