### Create week
POST http://localhost:7076/api/v1/week
Content-Type: application/json

{
  "weekNumber": 1,
  "days": []
}

### Get all weeks
GET http://localhost:7076/api/v1/week
Content-Type: application/json

### Get week by id
GET http://localhost:7076/api/v1/week/1
Content-Type: application/json
